import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { BrowserRouter } from 'react-router-dom';
import AccessibilityStatement from './AccessibilityStatement';

// Wrapper to provide routing context
const renderWithRouter = (component) => {
  return render(
    <BrowserRouter>
      {component}
    </BrowserRouter>
  );
};

describe('AccessibilityStatement', () => {
  describe('rendering', () => {
    it('renders the page title', () => {
      renderWithRouter(<AccessibilityStatement />);
      expect(screen.getByText('Accessibility Statement')).toBeInTheDocument();
    });

    it('renders the company name correctly', () => {
      renderWithRouter(<AccessibilityStatement />);
      expect(screen.getAllByText(/Joseph S. Thomas dba Content-Strategy.co/i).length).toBeGreaterThan(0);
    });

    it('renders commitment section', () => {
      renderWithRouter(<AccessibilityStatement />);
      expect(screen.getByText('Our Commitment to Accessibility')).toBeInTheDocument();
    });

    it('renders WCAG reference', () => {
      renderWithRouter(<AccessibilityStatement />);
      expect(screen.getByText(/Web Content Accessibility Guidelines/i)).toBeInTheDocument();
      expect(screen.getByText(/WCAG/i)).toBeInTheDocument();
    });

    it('renders accessibility features section', () => {
      renderWithRouter(<AccessibilityStatement />);
      expect(screen.getByText('Accessibility Features')).toBeInTheDocument();
      expect(screen.getByText('Keyboard Navigation')).toBeInTheDocument();
      expect(screen.getByText('Screen Reader Support')).toBeInTheDocument();
      expect(screen.getByText('Visual Design')).toBeInTheDocument();
    });

    it('renders technical specifications section', () => {
      renderWithRouter(<AccessibilityStatement />);
      expect(screen.getByText('Technical Specifications')).toBeInTheDocument();
      expect(screen.getByText('HTML5')).toBeInTheDocument();
      expect(screen.getByText('WAI-ARIA (Web Accessibility Initiative - Accessible Rich Internet Applications)')).toBeInTheDocument();
    });

    it('renders known limitations section', () => {
      renderWithRouter(<AccessibilityStatement />);
      expect(screen.getByText('Known Limitations')).toBeInTheDocument();
      expect(screen.getByText(/AI-Generated Content/i)).toBeInTheDocument();
    });

    it('renders feedback section with contact info', () => {
      renderWithRouter(<AccessibilityStatement />);
      expect(screen.getByText('Feedback & Contact Information')).toBeInTheDocument();
      expect(screen.getByText(/accessibility@content-strategy.co/i)).toBeInTheDocument();
    });

    it('renders enforcement procedure section', () => {
      renderWithRouter(<AccessibilityStatement />);
      expect(screen.getByText('Enforcement Procedure')).toBeInTheDocument();
    });

    it('renders back to home link', () => {
      renderWithRouter(<AccessibilityStatement />);
      expect(screen.getByText(/Back to Home/i)).toBeInTheDocument();
    });

    it('renders related policies links', () => {
      renderWithRouter(<AccessibilityStatement />);
      expect(screen.getByText('Terms of Service')).toBeInTheDocument();
      expect(screen.getByText('Privacy & Data Policy')).toBeInTheDocument();
      expect(screen.getByText('AI Usage Policy')).toBeInTheDocument();
    });
  });

  describe('content accuracy', () => {
    it('mentions conformance to Level AA', () => {
      renderWithRouter(<AccessibilityStatement />);
      expect(screen.getByText(/Level AA/i)).toBeInTheDocument();
    });

    it('lists user groups who benefit from accessibility', () => {
      renderWithRouter(<AccessibilityStatement />);
      expect(screen.getByText(/People who are blind or have low vision/i)).toBeInTheDocument();
      expect(screen.getByText(/People who are deaf or hard of hearing/i)).toBeInTheDocument();
    });

    it('notes AI-generated content limitation', () => {
      renderWithRouter(<AccessibilityStatement />);
      expect(screen.getByText(/Content generated by AI features may not always meet accessibility standards/i)).toBeInTheDocument();
    });
  });
});
